import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Josefin_Sans, Josefin_Slab, Playfair_Display } from 'next/font/google';
import ClientLayoutWrapper from '../components/ClientLayoutWrapper';
import Container from '../components/container/Container';
import Footer from '../components/footer/Footer';
import Navbar from '../components/navigationMenu/Navbar';
import GlobalLoaderProvider from '../components/Shared/providers/GlobalLoaderProvider';
import { ReduxProvider } from '../components/Shared/providers/ReduxProvider';
import UserSyncProvider from '../components/Shared/providers/UserSyncProvider';
import { Toaster } from '../components/ui/sonner';
import { authOptions } from '../lib/auth/authOptions';
import './global.css';

// Josefin fonts
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin-sans',
});

const josefinSlab = Josefin_Slab({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin-slab',
});

// Playfair Display for headings
const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair-display',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${josefinSans.variable} ${josefinSlab.variable} ${playfairDisplay.variable}`}
    >
      <body
        suppressHydrationWarning
        className={`${josefinSans.className} antialiased`}
      >
        <ReduxProvider>
          <GlobalLoaderProvider>
            <ClientLayoutWrapper session={session}>
              <UserSyncProvider>
                {/* <BackgroundLayout> */}
                {/* navbar */}
                <header className="fixed top-0 left-0 z-40 w-full bg-transparent">
                  <Container>
                    <Navbar />
                  </Container>
                </header>

                {/* Main Content */}
                <main>{children}</main>
                <Toaster
                  position="bottom-right"
                  richColors
                  toastOptions={{
                    duration: 5000,
                    style: {
                      // Custom background & text
                      background: '#f39d39', // green-500
                      color: '#183136',
                      fontSize: '14px',
                      borderRadius: '0.5rem',
                      padding: '1rem',
                    },
                  }}
                />

                {/* Footer */}
                <footer>
                  <Footer />
                </footer>
                {/* </BackgroundLayout> */}
              </UserSyncProvider>
            </ClientLayoutWrapper>
          </GlobalLoaderProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
