import BackgroundLayout from '@/components/layouts/BackgroundLayout';
import type { Metadata } from 'next';
import { SessionProvider, getServerSession } from 'next-auth/react';
import { Josefin_Sans, Josefin_Slab, Playfair_Display } from 'next/font/google';
import Container from '../components/container/Container';
import Footer from '../components/footer/Footer';
import Navbar from '../components/navigationMenu/Navbar';
import { ReduxProvider } from '../components/Shared/ReduxProvider';
import './global.css';

// Josefin fonts
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin-sans',
});

const josefinSlab = Josefin_Slab({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin-slab',
});

// Playfair Display for headings
const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair-display',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${josefinSans.variable} ${josefinSlab.variable} ${playfairDisplay.variable}`}
    >
      <body
        suppressHydrationWarning
        className={`${josefinSans.className} antialiased`}
      >
        <ReduxProvider>
          <SessionProvider session={session}>
            <BackgroundLayout>
              {/* Mount guard early so it catches any style injections */}

              {/* Navbar fixed at top */}
              <header className="fixed top-0 left-0 z-40 w-full bg-transparent">
                <Container>
                  <Navbar />
                </Container>
              </header>

              {/* Main Content */}
              <main className="">{children}</main>

              {/* Footer */}
              <footer>
                <Footer />
              </footer>
            </BackgroundLayout>
          </SessionProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
