import BackgroundLayout from '@/components/layouts/BackgroundLayout';
import type { Metadata } from 'next';
import { Josefin_Sans, Josefin_Slab, Playfair_Display } from 'next/font/google';
import Container from '../components/container/Container';
import Navbar from '../components/navigationMenu/Navbar';
import './globals.css';

// Josefin fonts - same as TastyCS template
const josefinSans = Josefin_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin-sans',
});

const josefinSlab = Josefin_Slab({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-josefin-slab',
});

// PlayfairDisplay for headings
const playfairDisplay = Playfair_Display({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-playfair-display',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${josefinSans.variable} ${josefinSlab.variable} ${playfairDisplay.variable}`}
    >
      <body className={`${josefinSans.className} antialiased`}>
        <BackgroundLayout>
          <Container>
            <div className="relative">
              <nav className="absolute top-0 z-50 w-full">
                <Navbar />
              </nav>
            </div>
          </Container>
          {children}
          <Container>
            <h2 className={`${playfairDisplay.className} text-4xl font-bold`}>
              Footer
            </h2>
          </Container>
        </BackgroundLayout>
      </body>
    </html>
  );
}
